name: Package

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16.x'
      env: # Or as an environment variable
        WOW_CLIENT_ID: ${{ secrets.CLIENT_ID }}
        WOW_CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
    - run: npm install --location=global yarn
    - run: npm install
    - run: |
        cat <<EOF > .env
        CLIENT_ID=${{env.WOW_CLIENT_ID}}
        CLIENT_SECRET=${{env.WOW_CLIENT_SECRET}}
        EOF
        cat .env
    - run: npm start